/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.DAO;
import Modelo.Caixa;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class Alterar extends javax.swing.JFrame {

    /**
     * Creates new form Alterar
     */
    Long id;
    Caixa caixa;
    DAO dao = new DAO();

    public Alterar(Long id) {
        this.id = id;
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        fillFields(id);
    }

    private Alterar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCidade = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLValor = new javax.swing.JLabel();
        jLPago = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jTValor = new javax.swing.JTextField();
        jCBPago = new javax.swing.JComboBox();
        jDCData = new com.toedter.calendar.JDateChooser();
        jLData = new javax.swing.JLabel();
        jBAltera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLCidade.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLCidade.setText("Alteração de Dados");

        jLNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLNome.setText("Nome:");

        jLValor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLValor.setText("Valor:");

        jLPago.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLPago.setText("Pago:");

        jTNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jCBPago.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCBPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Pago" }));

        jDCData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLData.setText("Data:");

        jBAltera.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBAltera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jBAltera.setText("Alterar");
        jBAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlteraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBAltera)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNome)
                                    .addComponent(jLValor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLData, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDCData, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLPago)
                                .addGap(18, 18, 18)
                                .addComponent(jCBPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLCidade)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLValor)
                    .addComponent(jTValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLData)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jDCData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPago)
                    .addComponent(jCBPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jBAltera)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlteraActionPerformed
        try {
            caixa.setId(id);
            caixa.setCliente(jTNome.getText());
            caixa.setData(jDCData.getDate());
            caixa.setValor(formataValor(jTValor.getText()));
            caixa.setPago(String.valueOf(jCBPago.getSelectedItem()));
            dao.alterar(caixa);
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBAlteraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alterar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAltera;
    private javax.swing.JComboBox jCBPago;
    private com.toedter.calendar.JDateChooser jDCData;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLPago;
    private javax.swing.JLabel jLValor;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTValor;
    // End of variables declaration//GEN-END:variables

    private void fillFields(Long id) {
        caixa = dao.buscarID(id);
        jTNome.setText(caixa.getCliente());
        jTValor.setText(String.valueOf(caixa.getValor()));
        jDCData.setDate(caixa.getData());

        if (caixa.getPago() != null) {
            jCBPago.setSelectedIndex(1);
        } else {
            jCBPago.setSelectedIndex(0);
        }

        /*  for (int i = 0; i < jCBPago.getItemCount(); i++) {
         System.out.println(caixa.getPago());
         System.out.println(jCBPago.getItemAt(0));
         if (caixa.getPago().equals(jCBPago.getItemAt(i))) {
         jCBPago.setSelectedIndex(i);
         }
         }*/
    }

    public Double formataValor(String valor) {
        return Double.parseDouble(valor.replace(",", "."));
    }
}
