/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package espuma;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Calculador_Espuma extends javax.swing.JFrame {

    /**
     * Creates new form Calculador_Espuma
     */
    public Calculador_Espuma() {
        super("Ronaldo Tapeceiro");
        this.setResizable(false);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/icone.png")));
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAltura = new javax.swing.JLabel();
        jLLargura = new javax.swing.JLabel();
        jLComprimento = new javax.swing.JLabel();
        jLQnt = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jTAltura = new javax.swing.JTextField();
        jTLargura = new javax.swing.JTextField();
        jTComp = new javax.swing.JTextField();
        jTQnt = new javax.swing.JTextField();
        jTTotal = new javax.swing.JTextField();
        jTCalc = new javax.swing.JButton();
        jLCabecalho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLAltura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLAltura.setText("Altura:");

        jLLargura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLLargura.setText("Largura:");

        jLComprimento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLComprimento.setText("Comprimento:");

        jLQnt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLQnt.setText("Quantidade:");

        jLTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLTotal.setText("Total:");

        jTAltura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTLargura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTComp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTQnt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTCalc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTCalc.setText("Calcular");
        jTCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCalcActionPerformed(evt);
            }
        });

        jLCabecalho.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLCabecalho.setText("Cálculo de Valor de Espumas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLCabecalho))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLLargura)
                            .addComponent(jLAltura)
                            .addComponent(jLComprimento)
                            .addComponent(jLQnt)
                            .addComponent(jLTotal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTAltura)
                            .addComponent(jTLargura)
                            .addComponent(jTComp)
                            .addComponent(jTQnt)
                            .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTCalc)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLCabecalho)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAltura))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLLargura))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLComprimento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLQnt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal))
                .addGap(40, 40, 40)
                .addComponent(jTCalc)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCalcActionPerformed
        try {
            double alt = Double.parseDouble(jTAltura.getText()) / 100;
            double comp = Double.parseDouble(jTComp.getText()) / 100;
            double larg = Double.parseDouble(jTLargura.getText()) / 100;
            double precoEspuma = (((comp * larg) * alt) * 2220);


            if (!jTQnt.getText().equals("")) {
                precoEspuma = (((comp * larg) * alt) * 2220) * Double.parseDouble(jTQnt.getText());
            }
            jTTotal.setText(String.format("R$ %.2f", precoEspuma));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erro, Preencha todos os campos.\n" + ex);
        }
    }//GEN-LAST:event_jTCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculador_Espuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculador_Espuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculador_Espuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculador_Espuma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculador_Espuma().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAltura;
    private javax.swing.JLabel jLCabecalho;
    private javax.swing.JLabel jLComprimento;
    private javax.swing.JLabel jLLargura;
    private javax.swing.JLabel jLQnt;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JTextField jTAltura;
    private javax.swing.JButton jTCalc;
    private javax.swing.JTextField jTComp;
    private javax.swing.JTextField jTLargura;
    private javax.swing.JTextField jTQnt;
    private javax.swing.JTextField jTTotal;
    // End of variables declaration//GEN-END:variables
}
