/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.ClienteDAO;
import DAO.FornecedorDAO;
import Modelo.Fornecedor;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author User
 */
public class Cadastro_Fornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro_Fornecedor
     */
    JDesktopPane painel;
    List<Fornecedor> fornecedores;
    Fornecedor fornecedor;
    FornecedorDAO dao;
    DefaultTableModel tmCliente = new DefaultTableModel(null, new String[]{
        "Loja", "Vendedor", "Telefone 1", "Telefone 2", "Telefone 3", "Telefone 4", "E-mail", "Endereço", "OBS"});

    MaskFormatter maskTelefone1 = new MaskFormatter("### (##) ####-####");
    MaskFormatter maskTelefone2 = new MaskFormatter("### (##) ####-####");
    MaskFormatter maskTelefone3 = new MaskFormatter("### (##) ####-####");
    MaskFormatter maskCelular = new MaskFormatter("### (##) #####-####");
    MaskFormatter maskCep = new MaskFormatter("#####-###");

    public Cadastro_Fornecedor(JDesktopPane painel) throws ParseException {
        super("Controle de Fornecedor");
        initComponents();
        maskTelefone1.install(jFTTelefone1);
        maskTelefone2.install(jFTTelefone2);
        maskTelefone3.install(jFTTelefone3);
        maskCelular.install(jFTTelefone4);
        maskCep.install(jFTCEP);
        this.painel = painel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jTVendedor = new javax.swing.JTextField();
        jTRua = new javax.swing.JTextField();
        jTNumero = new javax.swing.JTextField();
        jTBairro = new javax.swing.JTextField();
        jTCidade = new javax.swing.JTextField();
        jFTTelefone3 = new javax.swing.JFormattedTextField();
        jFTTelefone2 = new javax.swing.JFormattedTextField();
        jFTTelefone1 = new javax.swing.JFormattedTextField();
        jFTTelefone4 = new javax.swing.JFormattedTextField();
        jCBEstado = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAobs = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jTLoja = new javax.swing.JTextField();
        jTPesquisar = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jBCadastar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBEditar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jFTCEP = new javax.swing.JFormattedTextField();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Loja:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Vendedor:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Telefone 1:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Telefone 2:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Telefone 3:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Celular:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("OBS:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Rua:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nº:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Bairro:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Cidade:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Estado:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("CEP:");

        jTEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTVendedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTRua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTBairro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTCidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jFTTelefone3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jFTTelefone2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jFTTelefone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jFTTelefone4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jCBEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCBEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SP", "RJ", "MG" }));

        jTAobs.setColumns(20);
        jTAobs.setRows(5);
        jScrollPane1.setViewportView(jTAobs);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("E-mail:");

        jTLoja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPesquisarActionPerformed(evt);
            }
        });
        jTPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPesquisarKeyTyped(evt);
            }
        });

        jBPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar.png"))); // NOI18N
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        Tabela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tabela.setModel(tmCliente);
        Tabela.setRowHeight(23);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela);

        jBCadastar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBCadastar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        jBCadastar.setText("Cadastrar");
        jBCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastarActionPerformed(evt);
            }
        });

        jBEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.gif"))); // NOI18N
        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/limpar.png"))); // NOI18N
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jFTCEP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(jFTTelefone3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jFTTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFTTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFTTelefone4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(jTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastar)
                .addGap(32, 32, 32)
                .addComponent(jBEditar)
                .addGap(30, 30, 30)
                .addComponent(jBExcluir)
                .addGap(29, 29, 29)
                .addComponent(jBLimpar)
                .addGap(197, 197, 197))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFTTelefone1, jFTTelefone2, jFTTelefone3, jFTTelefone4});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCadastar, jBEditar, jBExcluir, jBLimpar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jTVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jFTTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jFTTelefone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jFTTelefone4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jFTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastar)
                    .addComponent(jBEditar)
                    .addComponent(jBExcluir)
                    .addComponent(jBLimpar))
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPesquisar)
                    .addComponent(jTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        try {
            dao = new FornecedorDAO();
            fornecedores = dao.listar("%" + jTPesquisar.getText() + "%");

            while (tmCliente.getRowCount() > 0) {
                tmCliente.removeRow(0);
            }

            String endereco;
            for (int i = 0; i < fornecedores.size(); i++) {

                //"Loja", "Vendedor", "Telefone 1", "Telefone 2", "Telefone 3", "Telefone 4", "E-mail", "Endereço", "OBS"});
                tmCliente.addRow(new String[]{null, null, null, null});
                endereco = "Rua: " + fornecedores.get(i).getRua() + "Nº "
                        + fornecedores.get(i).getNumero() + " - "
                        + fornecedores.get(i).getBairro() + ". "
                        + fornecedores.get(i).getCidade() + "/"
                        + fornecedores.get(i).getEstado() + "CEP: "
                        + fornecedores.get(i).getCep();

                tmCliente.setValueAt(fornecedores.get(i).getLoja(), i, 0);
                tmCliente.setValueAt(fornecedores.get(i).getVendedor(), i, 1);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone1(), i, 2);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone2(), i, 3);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone3(), i, 4);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone4(), i, 5);
                tmCliente.setValueAt(fornecedores.get(i).getEmail(), i, 6);
                tmCliente.setValueAt(endereco, i, 7);
                tmCliente.setValueAt(fornecedores.get(i).getObs(), i, 8);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jTPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPesquisarActionPerformed
        try {
            dao = new FornecedorDAO();
            fornecedores = dao.listar("%" + jTPesquisar.getText() + "%");

            while (tmCliente.getRowCount() > 0) {
                tmCliente.removeRow(0);
            }

            String endereco;
            for (int i = 0; i < fornecedores.size(); i++) {

                //"Loja", "Vendedor", "Telefone 1", "Telefone 2", "Telefone 3", "Telefone 4", "E-mail", "Endereço", "OBS"});
                tmCliente.addRow(new String[]{null, null, null, null});
                endereco = "Rua: " + fornecedores.get(i).getRua() + "Nº "
                        + fornecedores.get(i).getNumero() + " - "
                        + fornecedores.get(i).getBairro() + ". "
                        + fornecedores.get(i).getCidade() + "/"
                        + fornecedores.get(i).getEstado() + "CEP: "
                        + fornecedores.get(i).getCep();

                tmCliente.setValueAt(fornecedores.get(i).getLoja(), i, 0);
                tmCliente.setValueAt(fornecedores.get(i).getVendedor(), i, 1);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone1(), i, 2);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone2(), i, 3);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone3(), i, 4);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone4(), i, 5);
                tmCliente.setValueAt(fornecedores.get(i).getEmail(), i, 6);
                tmCliente.setValueAt(endereco, i, 7);
                tmCliente.setValueAt(fornecedores.get(i).getObs(), i, 8);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTPesquisarActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        jTLoja.setText(fornecedores.get(Tabela.getSelectedRow()).getLoja());
        jTVendedor.setText(fornecedores.get(Tabela.getSelectedRow()).getVendedor());
        jFTTelefone1.setText(fornecedores.get(Tabela.getSelectedRow()).getTelefone1());
        jFTTelefone2.setText(fornecedores.get(Tabela.getSelectedRow()).getTelefone2());
        jFTTelefone3.setText(fornecedores.get(Tabela.getSelectedRow()).getTelefone3());
        jFTTelefone4.setText(fornecedores.get(Tabela.getSelectedRow()).getTelefone4());
        jTEmail.setText(fornecedores.get(Tabela.getSelectedRow()).getEmail());
        jTRua.setText(fornecedores.get(Tabela.getSelectedRow()).getRua());
        jTNumero.setText(fornecedores.get(Tabela.getSelectedRow()).getNumero());
        jTBairro.setText(fornecedores.get(Tabela.getSelectedRow()).getBairro());
        jTCidade.setText(fornecedores.get(Tabela.getSelectedRow()).getCidade());
        for (int i = 0; i < jCBEstado.getItemCount(); i++) {
            if (jCBEstado.getItemAt(i).equals(fornecedores.get(Tabela.getSelectedRow()).getEstado())) {
                jCBEstado.setSelectedIndex(i);
            }
        }
        jFTCEP.setText(fornecedores.get(Tabela.getSelectedRow()).getCep());
        jTAobs.setText(fornecedores.get(Tabela.getSelectedRow()).getObs());
    }//GEN-LAST:event_TabelaMouseClicked

    private void jBCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastarActionPerformed
        try {
            fornecedor = new Fornecedor(jTLoja.getText(), jTVendedor.getText(),
                    jFTTelefone1.getText(), jFTTelefone2.getText(), jFTTelefone3.getText(),
                    jFTTelefone4.getText(), jTEmail.getText(), jTRua.getText(),
                    jTNumero.getText(), jTBairro.getText(), jTCidade.getText(),
                    (String) jCBEstado.getSelectedItem(), jFTCEP.getText(),
                    jTAobs.getText());

            dao = new FornecedorDAO();
            dao.adicionar(fornecedor);
            JOptionPane.showMessageDialog(null, "Fornecedor Cadastrado com Sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBCadastarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        try {
            fornecedor = new Fornecedor(fornecedores.get(Tabela.getSelectedRow()).getCodigo(), jTLoja.getText(), jTVendedor.getText(),
                    jFTTelefone1.getText(), jFTTelefone2.getText(), jFTTelefone3.getText(),
                    jFTTelefone4.getText(), jTEmail.getText(), jTRua.getText(),
                    jTNumero.getText(), jTBairro.getText(), jTCidade.getText(),
                    (String) jCBEstado.getSelectedItem(), jFTCEP.getText(),
                    jTAobs.getText());

            dao = new FornecedorDAO();
            dao.atualizar(fornecedor);
            JOptionPane.showMessageDialog(null, "Fornecedor Atualizado com Sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int pergunta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir este fornecedor?");
        if (pergunta == 0) {//clicou em sim  
            try {
                dao = new FornecedorDAO();
                dao.remover(fornecedores.get(Tabela.getSelectedRow()).getCodigo());
                JOptionPane.showMessageDialog(null, "Fornecedor Deletado com Sucesso!");
                limpar();
            } catch (SQLException | ParseException ex) {
                JOptionPane.showMessageDialog(null, "Erro:\n" + ex);
            }
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        try {
            limpar();
        } catch (ParseException ex) {
            Logger.getLogger(Cadastro_Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jTPesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPesquisarKeyTyped
        try {
            dao = new FornecedorDAO();
            fornecedores = dao.listar("%" + jTPesquisar.getText() + "%");

            while (tmCliente.getRowCount() > 0) {
                tmCliente.removeRow(0);
            }

            String endereco;
            for (int i = 0; i < fornecedores.size(); i++) {

                //"Loja", "Vendedor", "Telefone 1", "Telefone 2", "Telefone 3", "Telefone 4", "E-mail", "Endereço", "OBS"});
                tmCliente.addRow(new String[]{null, null, null, null});
                endereco = "Rua: " + fornecedores.get(i).getRua() + "Nº "
                        + fornecedores.get(i).getNumero() + " - "
                        + fornecedores.get(i).getBairro() + ". "
                        + fornecedores.get(i).getCidade() + "/"
                        + fornecedores.get(i).getEstado() + "CEP: "
                        + fornecedores.get(i).getCep();

                tmCliente.setValueAt(fornecedores.get(i).getLoja(), i, 0);
                tmCliente.setValueAt(fornecedores.get(i).getVendedor(), i, 1);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone1(), i, 2);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone2(), i, 3);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone3(), i, 4);
                tmCliente.setValueAt(fornecedores.get(i).getTelefone4(), i, 5);
                tmCliente.setValueAt(fornecedores.get(i).getEmail(), i, 6);
                tmCliente.setValueAt(endereco, i, 7);
                tmCliente.setValueAt(fornecedores.get(i).getObs(), i, 8);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTPesquisarKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jBCadastar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JComboBox jCBEstado;
    private javax.swing.JFormattedTextField jFTCEP;
    private javax.swing.JFormattedTextField jFTTelefone1;
    private javax.swing.JFormattedTextField jFTTelefone2;
    private javax.swing.JFormattedTextField jFTTelefone3;
    private javax.swing.JFormattedTextField jFTTelefone4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTAobs;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTLoja;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTextField jTPesquisar;
    private javax.swing.JTextField jTRua;
    private javax.swing.JTextField jTVendedor;
    // End of variables declaration//GEN-END:variables

    private void limpar() throws ParseException {
        this.dispose();
        Cadastro_Fornecedor cf = new Cadastro_Fornecedor(painel);
        painel.add(cf);
        cf.setVisible(true);
    }
}
